// Generated by CoffeeScript 1.4.0

Driver.Request = (function() {

  function Request(transaction, storeName, objectJSON, options) {
    this.objectJSON = objectJSON;
    this.options = options;
    this.store = transaction.objectStore(storeName);
  }

  return Request;

})();

Driver.Request.prototype = _.extend(Driver.Request.prototype, {
  execute: function() {
    var request;
    request = this.run();
    return this.bindCallbacks(request);
  },
  bindCallbacks: function(request) {
    var _this = this;
    request.onerror = function(e) {
      return _this.options.error(e);
    };
    return request.onsuccess = function(e) {
      return _this.options.success(json);
    };
  }
});

Driver.AddRequest = {};

Driver.AddRequest.prototype = _.extend(Driver.Request.prototype, {
  run: function() {
    if (this.objectJSON.id === void 0) {
      this.objectJSON.id = guid();
    }
    if (this.objectJSON.id === null) {
      delete this.objectJSON.id;
    }
    if (this.store.keyPath) {
      return this.store.add(this.objectJSON);
    } else {
      return this.store.add(this.objectJSON, this.objectJSON.id);
    }
  }
});
