// Generated by CoffeeScript 1.4.0

window.S4 = function() {
  return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
};

window.guid = function() {
  return S4() + S4() + "-" + S4() + "-" + S4() + "-" + S4() + "-" + S4() + S4() + S4();
};

window.debugLog = function() {
  if (typeof window !== "undefined" && typeof window.console !== "undefined" && typeof window.console.log !== "undefined") {
    return window.console.log.apply(window.console, arguments);
  } else if (console.log !== "undefined") {
    return console.log.apply(console, arguments);
  }
};

if (typeof exports !== 'undefined') {
  window._ = require('underscore');
  window.Backbone = require('backbone');
}
