// Generated by CoffeeScript 1.4.0

window.S4 = function() {
  return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
};

window.guid = function() {
  return S4() + S4() + "-" + S4() + "-" + S4() + "-" + S4() + "-" + S4() + S4() + S4();
};

if (typeof exports !== 'undefined') {
  window._ = require('underscore');
  window.Backbone = require('backbone');
}
