// Generated by CoffeeScript 1.4.0

window.indexedDB = window.indexedDB || window.webkitIndexedDB || window.mozIndexedDB || window.msIndexedDB;

window.IDBTransaction = window.IDBTransaction || window.webkitIDBTransaction || {
  READ_WRITE: "readwrite"
};

window.IDBKeyRange = window.IDBKeyRange || window.webkitIDBKeyRange;

window.IDBCursor = window.IDBCursor || window.webkitIDBCursor || window.mozIDBCursor || window.msIDBCursor;
