// Generated by CoffeeScript 1.4.0

window.ExecutionQueue = (function() {

  function ExecutionQueue(schema, next, nolog) {
    this.driver = new Driver(schema, this.ready.bind(this), nolog);
    this.started = false;
    this.stack = [];
    this.version = _.last(schema.migrations).version;
    this.next = next;
  }

  return ExecutionQueue;

})();

window.ExecutionQueue.prototype = _.extend(window.ExecutionQueue.prototype, {
  ready: function() {
    var _this = this;
    this.started = true;
    _.each(this.stack, function(message) {
      return _this.execute(message);
    });
    return this.next();
  },
  execute: function(message) {
    if (this.started) {
      return this.driver.execute(message[1].storeName, message[0], message[1], message[2]);
    } else {
      return this.stack.push(message);
    }
  },
  close: function() {
    return this.driver.close();
  }
});
