// Generated by CoffeeScript 1.4.0
var Databases, sync;

Databases = {};

sync = function(method, object, options) {
  var next, schema;
  if (method === "closeall") {
    _.each(Databases, function(database) {
      return database.close();
    });
    Databases = {};
    return;
  }
  schema = object.database;
  if (Databases[schema.id]) {
    if (Databases[schema.id].version !== _.last(schema.migrations).version) {
      Databases[schema.id].close();
      delete Databases[schema.id];
    }
  }
  next = function() {
    return Databases[schema.id].execute([method, object, options]);
  };
  if (!Databases[schema.id]) {
    return Databases[schema.id] = new ExecutionQueue(schema, next, schema.nolog);
  } else {
    return next();
  }
};

if (typeof exports === 'undefined') {
  Backbone.ajaxSync = Backbone.sync;
  Backbone.sync = sync;
} else {
  exports.sync = sync;
}
